services:                           # サービス定義
  python:                           # サービス名称を定義
    image: python:stats             # REPOSITORY名:TAG名を指定
    build: .                        # Dockerfileを相対パスで指定
    container_name: python-stats-web # 作成されるコンテナ名を指定
    working_dir: /workspace     # 作業ディレクトリを指定
    volumes:                        # マウントするファイルを指定する
      - ../:/workspace       # ローカルPCのsrc:コンテナのworkspace/src
    tty: true                       # コンテナを起動し続ける